all: test_assign3_1 test_assign3_2

test_assign3_1: buffer_mgr.c buffer_mgr_stat.c dberror.c storage_mgr.c expr.c record_mgr.c rm_serializer.c test_assign3_1.c

test_assign3_2: buffer_mgr.c buffer_mgr_stat.c dberror.c storage_mgr.c expr.c record_mgr.c rm_serializer.c test_assign3_2.c
